# Generated by Django 5.1.4 on 2024-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('img_url', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('topic', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuerySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(null=True)),
                ('num_results', models.IntegerField(default=10)),
                ('topic', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(null=True)),
                ('topic', models.TextField(null=True)),
            ],
        ),
    ]
